version: '3.8'

services:
  db:
    container_name: agenda-service-postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agenda-service-db
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  pgadmin:
    container_name: agenda-service-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.compose
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "15432:80"
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
